services:
  app:
    build: ./App
    ports:
      - "5005:5000"
    environment:
      - FLAG=${FLAG}
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - FLASK_ENV=development
      - DH_P=${DH_P}
      - DH_G=${DH_G}
    volumes:
      - ./App:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ctf_chat
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s